
package com.dell.apm.testwebapp.internal.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayHello", targetNamespace = "http://webservice.testserviceapp.apm.dell.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SayHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String sayHello(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);

}
